### ISSUE TITLE
Publish and maintain public docker image for containerised version of the deployment agent

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/customer-managed-deployment-agent#8]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We have the Dockerfile, and that's enough to get people started but to have a maintained image like we do the `pulumi/pulumi` image would be useful for customers.

**Comment by lblackstone** [comment]
https://hub.docker.com/r/pulumi/customer-managed-deployment-agent

Added to release workflow, so new images will automatically be published during release.
